#!/bin/sh

set -e

: "${REDIS_URL:?REDIS_URL must be set}"

IDEMPOTENCY_REDIS_KEY_PREFIX="${IDEMPOTENCY_REDIS_KEY_PREFIX:-generation:idempotency}"
IDEMPOTENCY_SEED_USER_ID="${IDEMPOTENCY_SEED_USER_ID:-seed-user-001}"
IDEMPOTENCY_SEED_PROJECT_ID="${IDEMPOTENCY_SEED_PROJECT_ID:-seed-project-001}"
IDEMPOTENCY_SEED_ENDPOINT="${IDEMPOTENCY_SEED_ENDPOINT:-generation}"
IDEMPOTENCY_SEED_KEY="${IDEMPOTENCY_SEED_KEY:-seed-idempotency-001}"
IDEMPOTENCY_SEED_REQUEST_ID="${IDEMPOTENCY_SEED_REQUEST_ID:-seed-request-001}"
IDEMPOTENCY_SEED_TTL_SECONDS="${IDEMPOTENCY_SEED_TTL_SECONDS:-900}"

LOCK_KEY="${IDEMPOTENCY_REDIS_KEY_PREFIX}:lock:${IDEMPOTENCY_SEED_USER_ID}:${IDEMPOTENCY_SEED_PROJECT_ID}:${IDEMPOTENCY_SEED_ENDPOINT}:${IDEMPOTENCY_SEED_KEY}"
LOCK_VALUE="${IDEMPOTENCY_SEED_REQUEST_ID}:seed"

redis-cli -u "$REDIS_URL" SET "$LOCK_KEY" "$LOCK_VALUE" EX "$IDEMPOTENCY_SEED_TTL_SECONDS"

printf 'Seeded Redis idempotency lock key:\n%s\n' "$LOCK_KEY"
printf 'TTL seconds: %s\n' "$IDEMPOTENCY_SEED_TTL_SECONDS"