type CopyOption<T extends string> = {
  value: T;
  label: string;
};

export const formatMeta = (label: string, value: string | number): string => `${label}: ${value}`;

export const appCopy = {
  ui: {
    session: {
      verifying: 'Verifica sessione...',
      unavailable: 'Sessione non disponibile.',
    },
    loader: {
      ariaLabel: 'Caricamento pagina',
      eyebrow: 'Workspace in sync',
      title: 'Sto preparando la prossima schermata',
      body: 'Caricamento modulo, stato e contenuti essenziali in corso.',
    },
    badges: {
      runtimeAsIs: 'workspace attivo',
      streaming: 'Streaming',
    },
    statusLabels: {
      // ArtifactLifecycleStatus / SessionSummary.status
      completed: 'Completato',
      failed: 'Con errore',
      generating: 'In corso',
      // ToolStepStatus
      idle: 'In attesa',
      running: 'In generazione...',
      done: 'Completato',
      error: 'Errore',
      // AuthUserStatus
      active: 'Attivo',
      disabled: 'Disabilitato',
      pending_password_reset: 'Reset password',
      // AdminLlmModelRow.status
      enabled: 'Abilitato',
      // ProductChangelogStatus
      draft: 'Bozza',
      published: 'Pubblicato',
      'github-published': 'Su GitHub',
      // UserReportStatus
      submitted: 'Inviata',
      triaged: 'In analisi',
      closed: 'Chiusa',
    },
    navigation: {
      dashboard: 'Dashboard',
      tools: 'Tools',
      projects: 'Projects',
      funnelPages: 'Hotlead Funnel',
      nextland: 'Nextland',
      youtubeLfScript: 'YouTube LF Script',
      angleGenerator: 'Angle Generator',
      feedbackCenter: 'Feedback',
      sessionSummary: 'Sessions',
      artifacts: 'Artifacts',
      admin: 'Admin',
    },
    actions: {
      logout: 'Esci',
      switchToDarkTheme: 'Attiva tema scuro',
      switchToLightTheme: 'Attiva tema chiaro',
      continueWithGoogleWorkspace: 'Continua con Google Workspace',
      enterWorkspace: 'Entra nel workspace',
      openProjects: 'Apri projects',
      openArchive: "Torna all'archivio",
      openSessionArchive: "Torna all'archivio",
      backToList: 'Torna alla lista',
      openDetail: 'Apri dettaglio',
      openToolWorkspace: 'Apri workspace',
      openArtifact: 'Apri artifact',
      openContextProject: 'Apri progetto',
      viewArtifact: 'Visualizza',
      setAsDefault: 'Predefinito',
      enable: 'Abilita',
      disable: 'Disabilita',
      delete: 'Elimina',
      edit: 'Modifica',
      editUser: 'Modifica utente',
      newProject: 'Nuovo progetto',
      createProject: 'Crea progetto',
      createFirstProject: 'Crea il tuo primo progetto',
      retry: 'Riprova',
      cancel: 'Cancella',
      reset: 'Ricomincia',
      processBriefing: 'Processa briefing',
      processBrief: 'Processa brief',
      startGeneration: 'Avvia la generazione',
      runNextStep: 'Avvia step successivo',
      useCheckpointResume: 'Riprendi da dove eri rimasto',
      useCheckpointRegenerate: 'Rigenera con nuovi parametri',
      historyBack: 'Torna allo storico',
      relaunchPrimary: 'Avvia di nuovo',
      deleteUiOnly: 'Rimuovi dalla vista',
      copyContent: 'Copia contenuto',
      copied: 'Copiato!',
      copyFailed: 'Copia fallita',
      download: 'Scarica',
      downloadAsMarkdown: 'Scarica come .md',
      downloadAsTxt: 'Scarica come testo',
      downloadAsDocx: 'Scarica come .docx',
      downloadFailed: 'Download fallito',
      viewMarkdown: 'Markdown',
      viewRaw: 'Raw',
      previousPage: 'Precedente',
      nextPage: 'Successivo',
      openNavigationMenu: 'Apri menu di navigazione',
      closeNavigationMenu: 'Chiudi menu di navigazione',
      expandNavigation: 'Espandi navigazione',
      collapseNavigation: 'Comprimi navigazione',
    },
    labels: {
      email: 'Email',
      password: 'Password',
      themeLight: 'Tema chiaro',
      themeDark: 'Tema scuro',
      intent: 'Tipo di operazione',
      checkpointAvailable: 'Usa punto di ripresa',
      recentCheckpoint: 'Punto di ripresa disponibile',
      sourceArtifactId: 'Artefatto di partenza',
      projectId: 'Project ID',
      projectName: 'Nome progetto',
      projectDescription: 'Descrizione',
      briefingFile: 'Briefing file (.docx, .txt, .md)',
      briefFile: 'Brief file (.docx, .txt, .md)',
      artifactType: 'Tipo di contenuto',
      model: 'Modello AI',
      toneOptional: 'Tono (opzionale)',
      notesOptional: 'Note aggiuntive (opzionale)',
      prompt: 'Prompt',
      promptFallback: 'Prompt di riserva',
      outputFormat: 'Formato di output',
      format: 'Formato',
      workflowType: 'Tipo di flusso',
      toolKey: 'Tool',
      idempotencyKey: 'Chiave di idempotenza',
      registrySnapshotRef: 'Versione di riferimento',
      type: 'Tipo',
      status: 'Stato',
      project: 'Progetto',
      user: 'Utente',
      period: 'Periodo',
      page: 'Pagina',
    },
    toolPage: {
      headingMetaSuffix: 'configuration and generation',
      guidance: {
        angleDetectorRequired: 'Brief pronto. Carica Angle Detector File per continuare.',
      },
      runtimeErrors: {
        projectRequired: 'Seleziona prima un progetto',
        requiredFilesMissing: 'Carica i file richiesti per continuare.',
        unsupportedBriefingFormat: 'Formato non supportato. Usa .docx, .txt o .md',
        uploadFailed: 'Errore durante upload',
        sessionUnavailable: 'Sessione non disponibile. Ricarica la pagina.',
        extractionFailed: 'Errore durante estrazione',
        dispatchFailed: 'Impossibile avviare la generazione. Controlla la connessione e riprova.',
        briefingContextInsufficient: 'Il briefing non contiene dati sufficienti per la generazione. Carica un nuovo brief più dettagliato.',
        streamFailed: 'La generazione non è andata a buon fine. Riprova tra pochi istanti.',
      },
      toneProfiles: [
        { value: 'Professional', label: 'Professional' },
        { value: 'Casual', label: 'Casual' },
        { value: 'Formal', label: 'Formal' },
        { value: 'Technical', label: 'Technical' },
      ] satisfies ReadonlyArray<CopyOption<'Professional' | 'Casual' | 'Formal' | 'Technical'>>,
      primaryActionPolicy: {
        disabledLabel: 'Completa il form per iniziare',
        disabledTooltip: 'Seleziona un progetto e carica un documento di brief',
        startGenerationLabel: 'Avvia la generazione',
        resumeCheckpointLabel: 'Riprendi dal checkpoint',
        resumeCheckpointTooltip: 'Continua dal punto in cui la generazione è stata interrotta',
        openLastArtifactLabel: 'Visualizza i risultati',
        openLastArtifactTooltip: "Apri l'artefatto generato",
        regenerateCurrentStepLabel: 'Rigenera',
        regenerateCurrentStepTooltip: 'Rigenera con i nuovi parametri',
      },
      form: {
        projectLabel: 'Project',
        modelLabel: 'Model',
        toneLabel: 'Tone',
        loadingProjects: 'Caricamento progetti...',
        selectProject: 'Seleziona un progetto',
        catalogUnavailable: 'Catalog unavailable',
        noModelsAvailable: 'No models available',
        cancelGeneration: 'Annulla',
        cancelGenerationTooltip: 'Interrompi la generazione in corso',
        validation: {
          projectRequired: 'Project richiesto',
          modelRequired: 'Model richiesto',
          toneRequired: 'Tone richiesto',
          uploadToContinuePrefix: 'Carica ',
          uploadToContinueSuffix: ' per continuare.',
        },
      },
      extraction: {
        uploadStepLabel: 'Upload briefing',
        uploadStatusLabel: 'Upload briefing in corso',
        extractingStepLabel: 'Estrazione contesto',
        extractingStatusLabel: 'Estrazione contesto in corso',
        inProgressStatusLabel: 'Estrazione briefing in corso',
        completedStepLabel: 'Estrazione completata',
        completedStatusLabel: 'Estrazione briefing completata',
        idleStepLabel: 'In attesa',
        idleStatusLabel: 'Estrazione briefing in attesa',
        startActionLabel: 'Avvia estrazione',
        startActionTooltip: "Avvia l'estrazione del contesto briefing",
      },
      flow: {
        ariaRegionLabel: 'Generation flow',
        ariaContextFilesLabel: 'Context files',
        progressAria: {
          extractionInProgress: 'Estrazione in corso',
          generationInProgress: 'Generazione in corso',
          generationCompleted: 'Generazione completata',
          generationPaused: 'Generazione in pausa',
          extractionCompleted: 'Estrazione completata',
          extractionIdle: 'Estrazione in attesa',
          waitingStart: 'In attesa di avvio',
        },
        phaseExtractionLabel: 'Fase: Estrazione',
        phaseGenerationLabel: 'Fase: Generazione',
        statusByCanonicalState: {
          'draft-empty': '',
          'processing-briefing': 'Estrazione in corso…',
          'draft-ready': 'Pronto per la generazione',
          'resume-needs-briefing': 'Carica un nuovo briefing per continuare',
          'prefilled-regenerate': 'Pronto per rigenerare',
          'paused-with-checkpoint': 'Generazione in pausa',
          'running': 'Generazione in corso…',
          'completed': 'Generazione completata',
        },
        currentStepPrefix: 'Step corrente: ',
        stepsCompletedSuffix: 'step completati',
        contextLoadedTitle: 'Contesto caricato',
        projectLabel: 'Progetto',
        noProjectSelected: 'Nessun progetto selezionato',
        notUploaded: 'Non caricato',
        noFilesUploaded: 'Nessun file caricato',
        apiAcquisitionTitle: 'Acquisizione API',
        apiAcquisitionConnected: 'Connesso',
        apiAcquisitionNotConnected: 'Non connesso',
        defaultExtractionStepLabel: 'Estrazione briefing',
        loadingActionLabel: 'In elaborazione...',
        requirednessLabel: {
          required: 'richiesto',
          optional: 'opzionale',
        },
      },
      filePayloadLabel: {
        briefing: 'BriefingFile',
        angleDetector: 'AngleDetectorFile',
      },
      openSessionLabel: 'Apri sessione',
    },
    toolWorkspaceStatus: {
      heading: 'Stato della generazione',
      projectLabel: 'Progetto',
      projectMissing: 'Seleziona un progetto',
      briefingLabel: 'Brief',
      briefingMissing: 'Carica il documento di brief',
      stepLabel: (completedStepsCount: number, totalStepsCount: number): string => `Step (${completedStepsCount}/${totalStepsCount})`,
      stepCompletedDetail: 'Tutti gli step completati',
      stepRemainingSuffix: 'rimanenti',
      stateLabel: 'Stato',
      canonicalStateLabels: {
        'draft-empty': 'In attesa di configurazione',
        'processing-briefing': 'Elaborazione brief in corso',
        'draft-ready': 'Pronto per avviare',
        'prefilled-regenerate': 'Contesto caricato — pronto a rigenerare',
        'paused-with-checkpoint': 'In pausa — riprendi dal checkpoint',
        'resume-needs-briefing': 'Carica un brief per continuare',
        'running': 'Generazione in corso',
        'completed': 'Completato',
      },
    },
    sessions: {
      detail: {
        panelAriaLabel: 'Contesto sessione',
        overviewAriaLabel: 'Panoramica sessione',
        detailsSummaryLabel: 'Dettagli sessione',
        projectFallbackPrefix: 'Progetto ',
        loadFailed: 'Impossibile caricare la sessione',
      },
    },
    toolInstructions: {
      title: 'Istruzioni compilazione file',
    },
    toolStep: {
      viewArtifactTitle: "Apri l'artefatto completo",
      stepGenerationFailed: 'Generazione non riuscita per questo step.',
    },
    artifactPreview: {
      toolbarLabel: 'Modalita visualizzazione contenuto',
      panelLabel: 'Preview contenuto artifact',
      emptyContentLabel: 'Contenuto non disponibile.',
    },
    meta: {
      phase: 'phase',
      extraction: 'extraction',
      briefing: 'briefing',
      jobDate: 'Data job',
      lastUpdate: 'Ultimo aggiornamento',
      artifactCount: 'Artefatti',
      checkpointStatus: 'checkpoint status',
      extractionContext: 'extraction context',
      toolsUploadCapability: 'toolsUpload capability',
      briefStatus: 'brief status',
      briefFile: 'brief file',
      nextStep: 'next step',
      streamStatus: 'stream status',
      artifact: 'artifact',
      artifactId: 'artifactId',
      sessionId: 'sessionId',
      projectId: 'projectId',
      state: 'Stato',
      uiState: 'uiState',
      primaryAction: 'primaryAction',
      requestId: 'requestId',
      reconnectAttempts: 'reconnect attempts',
      updated: 'updated',
      model: 'model',
      date: 'date',
      role: 'role',
      type: 'type',
      status: 'status',
      project: 'project',
    },
    states: {
      loadingProjects: 'Caricamento progetti...',
      noToolsAvailable: 'Nessun tool disponibile.',
      loadingUsers: 'Caricamento utenti...',
      loadingModels: 'Caricamento modelli...',
      loadingArtifact: 'Caricamento artifact...',
      loadingList: 'Caricamento...',
      noChunkReceived: 'In attesa del contenuto...',
      disabling: 'Disabilitazione...',
      noArtifactsFiltered: 'Nessun artefatto disponibile con i filtri correnti.',
      noArtifactSelected: 'Seleziona un artefatto per vedere il dettaglio.',
      noArtifactFound: 'Artefatto non trovato.',
      noArtifactsAvailable: 'Nessun artefatto disponibile.',
      userUnavailable: 'Utente non disponibile',
      projectUnavailable: 'Progetto non disponibile',
      noProjectFound: 'Progetto non trovato.',
      noProjectArtifacts: 'Nessun artefatto collegato al progetto.',
      noProjectsAvailable: 'Nessun progetto disponibile.',
      toolsUploadDisabled: 'Caricamento brief non disponibile in questo ambiente.',
      artifactDeleteDisabled: 'Rimozione artefatti non abilitata.',
      extractionContextMissing: 'Nessun brief trovato per il progetto selezionato. Carica un documento per iniziare.',
      backendEndpointPending: 'Funzionalità non ancora disponibile.',
      uploadingBriefing: 'Caricamento in corso...',
      extractingInformation: 'Estrazione contenuto in corso...',
      completed: 'completed',
      pending: 'pending',
      present: 'present',
      missing: 'missing',
    },
    placeholders: {
      sourceArtifactId: 'artifact-...',
      projectId: 'project-id',
    },
    fallbackErrors: {
      loginFailed: 'Login failed',
      createProject: 'Unable to create project',
      loadProjects: 'Unable to load projects',
      loadProjectDetail: 'Unable to load project detail',
      loadModels: 'Unable to load models',
      loadAdminModels: 'Failed to load models',
      loadArtifacts: 'Unable to load artifacts',
      loadSessions: 'Unable to load sessions',
      loadAdminChangelog: 'Unable to load changelog',
      loadAdminUserReports: 'Unable to load admin user reports',
      loadAdminUsers: 'Admin users load failed',
      loadAdminApiServices: 'Unable to load admin ApiService catalog',
      loadAdminApiServiceBindings: 'Unable to load admin ApiService bindings',
      loadAdminUsersHttp: (status: number): string => `Unable to load admin users (HTTP ${status})`,
    },
    feedback: {
      adminUsersCreated: 'Utente creato.',
      adminUsersUpdated: 'Utente aggiornato.',
      adminUsersDisabled: 'Utente disabilitato.',
      adminUsersCreateFailed: 'Impossibile creare utente.',
      adminUsersUpdateFailed: 'Impossibile aggiornare utente.',
      adminUsersDisableFailed: 'Impossibile disabilitare utente.',
      adminModelsCreated: 'Modello creato.',
      adminModelsDeleted: 'Modello eliminato.',
      adminModelsDefaultUpdated: 'Modello predefinito aggiornato.',
      adminModelsStatusUpdated: 'Stato modello aggiornato.',
      adminModelsCreateFailed: 'Impossibile creare modello.',
      adminModelsDeleteFailed: 'Impossibile eliminare modello.',
      adminModelsDefaultUpdateFailed: 'Impossibile aggiornare il modello predefinito.',
      adminModelsStatusUpdateFailed: 'Impossibile aggiornare lo stato modello.',
      projectsCreated: 'Progetto creato.',
      adminChangelogPublished: 'Voce changelog pubblicata.',
      adminChangelogPublishFailed: 'Impossibile pubblicare la voce changelog.',
      adminUserReportStatusUpdated: 'Stato segnalazione aggiornato.',
      adminUserReportStatusUpdateFailed: 'Impossibile aggiornare lo stato segnalazione.',
      adminUserReportIssuePublished: 'Issue GitHub pubblicata.',
      adminUserReportIssuePublishFailed: 'Impossibile pubblicare la issue GitHub.',
      userReportSubmitted: 'Segnalazione inviata con successo.',
      userReportSubmitFailed: 'Impossibile inviare la segnalazione.',
      adminApiServicesCreated: 'ApiService creato.',
      adminApiServicesUpdated: 'ApiService aggiornato.',
      adminApiServicesDeleted: 'ApiService eliminato.',
      adminApiServicesCreateFailed: 'Impossibile creare ApiService.',
      adminApiServicesUpdateFailed: 'Impossibile aggiornare ApiService.',
      adminApiServicesDeleteFailed: 'Impossibile eliminare ApiService.',
      adminApiServiceBindingsSaved: 'Binding ApiService salvato.',
      adminApiServiceBindingsDeleted: 'Binding ApiService eliminato.',
      adminApiServiceBindingsSaveFailed: 'Impossibile salvare il binding ApiService.',
      adminApiServiceBindingsDeleteFailed: 'Impossibile eliminare il binding ApiService.',
    },
    adminApiServices: {
      toolbarDescription: 'Catalogo amministrativo per ApiService e binding associati ai tool step.',
      toggleCreateHide: 'Nascondi form',
      toggleCreateShow: 'Nuovo ApiService',
      reloadTable: 'Aggiorna tabella',
      createFormTitle: 'Nuovo ApiService',
      createFormSubtitle: 'Configura endpoint, metodo e mapping in una vista unica.',
      createSubmitLabel: 'Crea ApiService',
      editFormTitle: 'Modifica ApiService',
      editFormSubtitlePrefix: 'Aggiorna la configurazione di ',
      editSubmitLabel: 'Salva ApiService',
      advancedJsonSummary: 'JSON avanzato',
      advancedJsonHelper: 'Template e mapping JSON opzionali per casi di integrazione avanzata.',
      createSavingLabel: 'Salvataggio...',
      emptyApiServices: 'Nessun ApiService disponibile.',
      tableHeaders: {
        key: 'Key',
        label: 'Label',
        accessMode: 'Access mode',
        requestMethod: 'Method',
        status: 'Status',
        token: 'Token',
        actions: 'Azioni',
      },
      tokenConfigured: 'Configured',
      tokenNotConfigured: 'Not configured',
      openBindingsAction: 'Binding',
      bindings: {
        selectedServicePrefix: 'Servizio selezionato: ',
        noServiceSelected: 'Seleziona un ApiService per gestire i binding.',
        formLabels: {
          toolKey: 'Tool key',
          stepKey: 'Step key',
          bindingStatus: 'Binding status',
          requiredness: 'Requiredness',
          workflowStepType: 'Workflow step type',
        },
        createAction: 'Crea binding',
        updateAction: 'Aggiorna binding',
        emptyForService: 'Nessun binding configurato per questo ApiService.',
      },
      fieldLabels: {
        key: 'Key',
        label: 'Label',
        baseUrl: 'Base URL',
        resourcePath: 'Resource path',
        accessMode: 'Access mode',
        requestMethod: 'Request method',
        timeoutMs: 'Timeout ms',
        retryCount: 'Retry count',
        contractProfileVersion: 'Contract profile version',
        status: 'Status',
        requestTemplateJson: 'Request template JSON',
        requestMappingRulesJson: 'Request mapping rules JSON',
        requestHeadersTemplateJson: 'Request headers JSON',
        responseMappingRulesJson: 'Response mapping rules JSON',
        errorMappingRulesJson: 'Error mapping rules JSON',
      },
    },
    feedbackCenter: {
      newsHeading: 'News',
      newsSubheading: 'Changelog pubblicato dagli admin.',
      formHeading: 'Segnala un problema',
      formSubheading: 'Aiutaci a migliorare la piattaforma.',
      closeFormAriaLabel: 'Chiudi modulo feedback',
      closeFormTitle: 'Chiudi modulo',
      loadingChangelog: 'Caricamento changelog...',
      noNewsAvailable: 'Nessuna news pubblicata al momento.',
      unavailableDate: 'Data non disponibile',
      submitButtonText: 'Invia segnalazione',
      submitButtonLoading: 'Invio in corso...',
      submitButtonSubmit: 'Invia',
      formCategoryLabel: 'Categoria',
      formTitleLabel: 'Titolo',
      formDescriptionLabel: 'Descrizione',
      formValidationError: 'Titolo e descrizione sono obbligatori.',
      openNewsAriaLabel: 'Apri news',
      closeNewsAriaLabel: 'Chiudi news',
    },
    feedbackCenterOptions: {
      categories: [
        { value: 'issue', label: 'Bug' },
        { value: 'feature-request', label: 'Feature request' },
        { value: 'other', label: 'Other' },
      ] satisfies ReadonlyArray<CopyOption<'issue' | 'feature-request' | 'other'>>,
    },
    options: {
      intent: [
        { value: 'new', label: 'Nuovo' },
        { value: 'resume', label: 'Riprendi' },
        { value: 'regenerate', label: 'Rigenera' },
      ] satisfies ReadonlyArray<CopyOption<'new' | 'resume' | 'regenerate'>>,
      artifactTypes: [
        { value: 'all', label: 'Tutti' },
        { value: 'content', label: 'Contenuto' },
        { value: 'seo', label: 'SEO' },
        { value: 'code', label: 'Codice' },
        { value: 'extraction', label: 'Estrazione' },
      ] satisfies ReadonlyArray<CopyOption<'all' | 'content' | 'seo' | 'code' | 'extraction'>>,
      artifactStatuses: [
        { value: 'all', label: 'Tutti' },
        { value: 'generating', label: 'In corso' },
        { value: 'completed', label: 'Completati' },
        { value: 'failed', label: 'Con errore' },
      ] satisfies ReadonlyArray<CopyOption<'all' | 'generating' | 'completed' | 'failed'>>,
      artifactPeriods: [
        { value: 'all', label: 'all' },
        { value: '7d', label: '7d' },
        { value: '30d', label: '30d' },
        { value: '90d', label: '90d' },
      ] satisfies ReadonlyArray<CopyOption<'all' | '7d' | '30d' | '90d'>>,
      outputFormats: [
        { value: 'plain', label: 'Testo semplice' },
        { value: 'json', label: 'JSON' },
        { value: 'markdown', label: 'Markdown' },
      ] satisfies ReadonlyArray<CopyOption<'plain' | 'json' | 'markdown'>>,
    },
  },
  editorial: {
    publicShell: {
      eyebrow: 'Campaign orchestration for digital teams',
      headline: 'Un workspace di produzione per concept, funnel e artifact che devono convincere al primo sguardo.',
      body: 'Pensato per team marketing 25-35 che lavorano tra posizionamento, landing, sprint creativi e revisioni continue: meno frizione operativa, piu ritmo editoriale.',
    },
    auth: {
      eyebrow: 'Private client area',
      headline: 'Accedi alla control room.',
      body: 'Ritrova progetti, tool guidati e artifact pronti per copy review, consegna o handoff al team.',
      pendingAccess: 'Accesso in corso...',
    },
    header: {
      headline: 'Stratego Flow',
    },
    dashboard: {
      headline: 'La tua strategia di crescita, protetta.',
      body: 'Ogni progetto è trattato come se il budget fosse nostro. Dalla definizione della strategia all\'esecuzione, proteggiamo ogni euro e otteniamo risultati concreti.',
      zeroState: {
        eyebrow: 'Benvenuto',
        headline: 'Tutto inizia con un progetto.',
        body: 'Un progetto è il contesto in cui organizzi brief, generazioni e output. Creane uno adesso per iniziare a lavorare con i tool di generazione.',
        cta: 'Crea il tuo primo progetto',
      },
      stats: [
        'Strategie protette',
        'Generazioni eseguite',
        'Risultati prodotti',
      ],
      cards: {
        projects: {
          title: 'Le tue strategie',
          body: 'Ogni progetto è uno spazio dove definisci la strategia e proteggi il tuo investimento. Strategie pensate per moltiplicare i risultati.',
        },
        tools: {
          title: 'Generazione per la tua strategia',
            body: 'Apri Tools come hub centrale per i percorsi guidati e per l\'orchestrazione canonica delle generazioni.',
        },
          recentSessions: {
            title: 'La tua storia di risultati',
        },
      },
    },
    projects: {
      listTitle: 'Projects',
      detailTitle: 'Project detail',
      newTitle: 'Nuovo progetto',
      contextualArtifacts: 'Artifacts contestuali',
      contextualSessions: 'Sessioni contestuali',
    },
    artifacts: {
      archiveTitle: 'Artifacts archive',
      detailTitle: 'Artifact detail',
    },
    sessions: {
      archiveTitle: 'Session archive',
      detailTitle: 'Session detail',
      loadingState: 'Caricamento sessione...',
      notFound: 'Sessione non trovata.',
      emptyState: 'Nessuna sessione disponibile.',
      emptyStateProject: 'Nessuna sessione collegata al progetto.',
      artifactCountLabel: 'artifact',
    },
    admin: {
      activityTitle: 'Attività recente',
      activityBody: 'Attività recente del workspace.',
      modelsTitle: 'Admin models',
      usersTitle: 'Admin users',
      changelogTitle: 'Admin changelog',
      userReportsTitle: 'Admin user reports',
      apiServicesTitle: 'Admin ApiService',
      apiServicesBody: 'Catalogo amministrativo per ApiService e binding dei tool step.',
      apiServiceBindingsTitle: 'Binding ApiService',
    },
    feedback: {
      userReportTitle: 'User report submission',
    },
    generation: {
      setupTitle: 'Configura la generazione',
      streamTitle: 'Contenuto generato',
      historyTitle: 'Storico artefatti',
      artifactDetailTitle: 'Dettaglio artifact',
      defaultPrompt: 'Scrivi una landing page sintetica in stile diretto.',
      defaultTone: 'diretto',
    },
    tools: {
      funnelPages: {
        title: 'Hotlead Funnel Tool',
        orderRule: 'Ordine step obbligatorio: optin -> quiz -> vsl',
        defaultPrompt: 'Genera lo step Funnel richiesto con coerenza al brief estratto.',
      },
      nextland: {
        title: 'Nextland Tool',
        orderRule: 'Ordine step obbligatorio: landing -> thank_you',
        defaultPrompt: 'Genera lo step Nextland richiesto con coerenza al brief estratto.',
      },
      youtubeLfScript: {
        title: 'YouTube LF Script Tool',
        orderRule: 'Ordine step obbligatorio: pre-script-analysis -> packaging -> intro-structure -> body-structure -> native-cta-embeds -> outro-structure',
        defaultPrompt: 'Genera lo step YouTube LF Script richiesto con coerenza al brief estratto.',
      },
      angleGenerator: {
        title: 'Angle Generator Tool',
        orderRule: 'Ordine step obbligatorio: context-and-angle-matrix -> angle-prioritization -> creative-activation',
        defaultPrompt: 'Genera angle prioritizzati e attivazioni creative coerenti al contesto estratto.',
      },
    },
  },
} as const;
