type CopyOption<T extends string> = {
  value: T;
  label: string;
};

export const formatMeta = (label: string, value: string | number): string => `${label}: ${value}`;

export const appCopy = {
  ui: {
    session: {
      verifying: 'Verifying session...',
      unavailable: 'Session unavailable.',
    },
    loader: {
      ariaLabel: 'Loading page',
      eyebrow: 'Workspace in sync',
      title: 'Preparing the next screen',
      body: 'Loading module, state, and essential content.',
    },
    badges: {
      runtimeAsIs: 'workspace active',
      streaming: 'Streaming',
    },
    statusLabels: {
      // ArtifactLifecycleStatus / SessionSummary.status
      completed: 'Completed',
      failed: 'Failed',
      generating: 'In progress',
      // ToolWorkflowJobStatus (DDD-NEW)
      queued: 'Queued',
      running: 'Running',
      cancelled: 'Cancelled',
      // ToolStepStatus
      idle: 'Waiting',
      done: 'Completed',
      error: 'Error',
      // AuthUserStatus
      active: 'Active',
      disabled: 'Disabled',
      pending_password_reset: 'Reset password',
      // AdminLlmModelRow.status
      enabled: 'Enabled',
      // ProductChangelogStatus
      draft: 'Draft',
      published: 'Published',
      'github-published': 'On GitHub',
      // UserReportStatus
      submitted: 'Submitted',
      triaged: 'Triaged',
      closed: 'Closed',
    },
    navigation: {
      dashboard: 'Dashboard',
      workspaces: 'Workspaces',
      tools: 'Tools',
      projects: 'Projects',
      funnelPages: 'Hotlead Funnel',
      nextland: 'Nextland',
      youtubeLfScript: 'YouTube LF Script',
      angleGenerator: 'Angle Generator',
      metaAds: 'MetaAds Generator',
      youtubeDescription: 'YT Description Generator',
      geometric: 'Geometric',
      feedbackCenter: 'Feedback',
      sessionSummary: 'Sessions',
      sessions: 'Sessions',
      artifacts: 'Artifacts',
      admin: 'Admin',
    },
    actions: {
      logout: 'Log out',
      switchToDarkTheme: 'Switch to dark theme',
      switchToLightTheme: 'Switch to light theme',
      continueWithGoogleWorkspace: 'Continue with Google Workspace',
      enterWorkspace: 'Enter workspace',
      openProjects: 'Open workspaces',
      openArchive: 'Back to archive',
      openSessionArchive: 'Back to archive',
      backToList: 'Back to list',
      openDetail: 'Open detail',
      openToolWorkspace: 'Open workspace',
      openWorkspace: 'Open workspace',
      enterWorkspaceTool: 'Use in workspace',
      createWorkspace: 'Create workspace',
      switchWorkspace: 'Switch workspace',
      openArtifact: 'Open artifact',
      openContextProject: 'Open project',
      viewArtifact: 'View',
      setAsDefault: 'Default',
      enable: 'Enable',
      disable: 'Disable',
      delete: 'Delete',
      edit: 'Edit',
      editUser: 'Edit user',
      newProject: 'New workspace',
      createProject: 'Create workspace',
      createFirstProject: 'Create your first workspace',
      retry: 'Retry',
      cancel: 'Cancel',
      reset: 'Start over',
      processBriefing: 'Process briefing',
      processBrief: 'Process brief',
      startGeneration: 'Start generation',
      runNextStep: 'Run next step',
      useCheckpointResume: 'Resume where you left off',
      useCheckpointRegenerate: 'Regenerate with new parameters',
      historyBack: 'Back to history',
      relaunchPrimary: 'Launch again',
      deleteUiOnly: 'Remove from view',
      copyContent: 'Copy content',
      copied: 'Copied!',
      copyFailed: 'Copy failed',
      download: 'Download',
      selectDownloadFormat: 'Select download format',
      downloadAsMarkdown: 'Download as .md',
      downloadAsTxt: 'Download as text',
      downloadAsDocx: 'Download as .docx',
      downloadFailed: 'Download failed',
      viewMarkdown: 'Markdown',
      viewRaw: 'Raw',
      previousPage: 'Previous',
      nextPage: 'Next',
      openNavigationMenu: 'Open navigation menu',
      closeNavigationMenu: 'Close navigation menu',
      expandNavigation: 'Expand navigation',
      collapseNavigation: 'Collapse navigation',
      unknownTool: 'Unknown tool',
    },
    labels: {
      email: 'Email',
      password: 'Password',
      themeLight: 'Light theme',
      themeDark: 'Dark theme',
      intent: 'Operation type',
      checkpointAvailable: 'Use checkpoint',
      recentCheckpoint: 'Checkpoint available',
      sourceArtifactId: 'Source artifact',
      projectId: 'Workspace ID',
      projectName: 'Workspace name',
      projectDescription: 'Description',
      briefingFile: 'Briefing file (.docx, .txt, .md)',
      briefFile: 'Brief file (.docx, .txt, .md)',
      artifactType: 'Content type',
      model: 'AI model',
      notesOptional: 'Additional notes (optional)',
      prompt: 'Prompt',
      promptFallback: 'Fallback prompt',
      outputFormat: 'Output format',
      format: 'Format',
      copyLengthFormat: 'Copy length format',
      workflowType: 'Workflow type',
      toolKey: 'Tool',
      idempotencyKey: 'Idempotency key',
      registrySnapshotRef: 'Reference version',
      type: 'Type',
      status: 'Status',
      project: 'Project',
      user: 'User',
      period: 'Period',
      page: 'Page',
      tool: 'Tool',
      workflow: 'Workspace',
      output: 'Output',
      showPreviousPagesBlock: (count: number): string => `Show previous ${count} pages`,
      showNextPagesBlock: (count: number): string => `Show next ${count} pages`,
    },
    toolPage: {
      headingMetaSuffix: 'configuration and generation',
      sections: {
        configuration: 'Configuration',
        resources: 'Resources',
        knowledge: 'Knowledge',
      },
      guidance: {
        angleDetectorRequired: 'Brief ready. Upload an Angle Detector File to continue.',
      },
      runtimeErrors: {
        projectRequired: 'Select a workspace first',
        requiredFilesMissing: 'Upload the required files to continue.',
        unsupportedBriefingFormat: 'Unsupported format. Use .docx, .txt, or .md',
        uploadFailed: 'Error during upload',
        sessionUnavailable: 'Session unavailable. Reload the page.',
        extractionFailed: 'Error during extraction',
        dispatchFailed: 'Unable to start generation. Check your connection and try again.',
        briefingContextInsufficient: 'The briefing does not contain enough data for generation. Upload a new, more detailed brief.',
        streamFailed: 'Generation was unsuccessful. Try again shortly.',
        idempotencyConflict: 'Generation already in progress. Please wait for completion.',
        timeout: 'Generation took too long. Try again or contact support.',
        connectionLost: 'Connection lost. Check your connection and try again.',
      },
      statusMessages: {
        ready: 'Ready for generation',
        waiting: 'Select a project and upload a brief to get started',
      },
      primaryActionPolicy: {
        disabledLabel: 'Complete the form to get started',
        disabledTooltip: 'Select a workspace and upload a briefing document',
        startGenerationLabel: 'Start generation',
        resumeCheckpointLabel: 'Resume from checkpoint',
        resumeCheckpointTooltip: 'Continue from where generation was interrupted',
        openLastArtifactLabel: 'View results',
        openLastArtifactTooltip: 'Open the generated artifact',
        regenerateCurrentStepLabel: 'Regenerate',
        regenerateCurrentStepTooltip: 'Regenerate with new parameters',
        missingAssetsWarningTooltip: 'Add knowledge assets for better results',
      },
      form: {
        projectLabel: 'Workspace',
        modelLabel: 'Model',
        campaignObjectiveLabel: 'Campaign objective',
        campaignObjectivePlaceholder: 'Select campaign objective',
        campaignObjectiveOptions: [
          { value: 'Awareness', label: 'Awareness' },
          { value: 'Traffic', label: 'Traffic' },
          { value: 'Engagement', label: 'Engagement' },
          { value: 'Leads', label: 'Leads' },
          { value: 'App promotion', label: 'App promotion' },
          { value: 'Sales', label: 'Sales' },
        ] satisfies ReadonlyArray<CopyOption<string>>,
        copyLengthFormatLabel: 'Copy length format',
        copyLengthFormatOptions: [
          { value: 'short-form', label: 'Short Form (400-600 characters)' },
          { value: 'medium-form', label: 'Medium Form (800-1000 characters)' },
          { value: 'long-form', label: 'Long Form (1200+ characters)' },
        ] satisfies ReadonlyArray<CopyOption<'short-form' | 'medium-form' | 'long-form'>>,
        loadingProjects: 'Loading workspaces...',
        selectProject: 'Select a workspace',
        catalogUnavailable: 'Catalog unavailable',
        noModelsAvailable: 'No models available',
        cancelGeneration: 'Cancel',
        cancelGenerationTooltip: 'Cancel the generation in progress',
        validation: {
          projectRequired: 'Workspace required',
          modelRequired: 'Model required',
          copyLengthFormatRequired: 'Copy length format required',
          uploadToContinuePrefix: 'Upload ',
          uploadToContinueSuffix: ' to continue.',
          articleTitleRequired: 'Article title required',
          videoTitleRequired: 'Video title required',
          topicRequired: 'Topic required',
          keywordsRequired: 'Keywords required',
          ctaTextRequired: 'CTA text required',
          ctaLinkRequired: 'CTA link required',
          credentialsRequired: 'Credentials or proof required',
          chaptersRequired: 'Chapters with timestamps required',
          baseQueryRequired: 'Base query required',
          languageRequired: 'Language required',
          countryRequired: 'Country required',
        },
      },
      extraction: {
        uploadStepLabel: 'Upload briefing',
        uploadStatusLabel: 'Uploading briefing',
        extractingStepLabel: 'Extracting context',
        extractingStatusLabel: 'Extracting context',
        inProgressStatusLabel: 'Generating context',
        completedStepLabel: 'Context ready',
        completedStatusLabel: 'Context generation completed',
        idleStepLabel: 'Waiting',
        idleStatusLabel: 'Context generation waiting',
        startActionLabel: 'Generate context',
        startActionTooltip: 'Start context generation (extraction, API acquisition, merge)',
      },
      flow: {
        ariaRegionLabel: 'Generation flow',
        progressAria: {
          extractionInProgress: 'Context generation in progress',
          generationInProgress: 'Generation in progress',
          generationCompleted: 'Generation completed',
          generationPaused: 'Generation paused',
          extractionCompleted: 'Context generation completed',
          extractionIdle: 'Context generation waiting',
          waitingStart: 'Waiting to start',
        },
        phaseExtractionLabel: 'Phase: Context generation',
        phaseGenerationLabel: 'Phase: Generation',
        statusByCanonicalState: {
          'draft-empty': '',
          'processing-briefing': 'Generating context…',
          'draft-ready': 'Ready for generation',
          'resume-needs-briefing': 'Upload a new briefing to continue',
          'prefilled-regenerate': 'Ready to regenerate',
          'paused-with-checkpoint': 'Generation paused',
          'running': 'Generating…',
          'completed': 'Generation completed',
        },
        currentStepPrefix: 'Current step: ',
        stepsCompletedSuffix: 'steps completed',
        defaultExtractionStepLabel: 'Preparing context',
        loadingActionLabel: 'Processing...',
      },
      openSessionLabel: 'Open session',
    },
    toolWorkspaceStatus: {
      heading: 'Generation status',
      projectLabel: 'Workspace',
      projectMissing: 'Select a workspace',
      briefingLabel: 'Brief',
      briefingMissing: 'Upload the brief document',
      stepLabel: (completedStepsCount: number, totalStepsCount: number): string => `Step (${completedStepsCount}/${totalStepsCount})`,
      stepCompletedDetail: 'All steps completed',
      stepRemainingSuffix: 'remaining',
      stateLabel: 'Status',
      canonicalStateLabels: {
        'draft-empty': 'Waiting for configuration',
        'processing-briefing': 'Generating context',
        'draft-ready': 'Ready to start',
        'prefilled-regenerate': 'Context loaded — ready to regenerate',
        'paused-with-checkpoint': 'Paused — resume from checkpoint',
        'resume-needs-briefing': 'Upload a brief to continue',
        'running': 'Generating',
        'completed': 'Completed',
      },
    },
    sessions: {
      detail: {
        primaryPanelAriaLabel: 'Session artifact content',
        secondaryPanelAriaLabel: 'Session context sidebar',
        overviewAriaLabel: 'Session overview',
        detailsSummaryLabel: 'Session details',
        projectFallback: 'Workspace unavailable',
        projectFallbackPrefix: 'Workspace ',
        loadFailed: 'Unable to load session',
        sessionPrefix: 'Session: ',
        allStepsHidden: 'All steps are hidden by configuration.',
        noStepArtifacts: 'No step artifacts found for this session.',
        scrollStepsLeft: 'Scroll session steps left',
        scrollStepsRight: 'Scroll session steps right',
        sessionStepsAria: 'Session steps',
        modelLabel: 'Model: ',
        modelOverride: 'Override',
        modelOverrideReason: 'Reason: ',
        selectedArtifactPanel: 'Selected session artifact',
        promoteToAsset: 'Promote to Asset',
      },
    },
    artifactDetail: {
      stepUnavailable: 'Step unavailable',
      toolUnavailable: 'Tool unavailable',
      previewAriaLabel: 'Artifact content preview',
      contextAriaLabel: 'Artifact context and actions',
      overviewAriaLabel: 'Artifact overview',
      technicalDetails: 'Technical details',
    },
    toolInstructions: {
      title: 'File compilation instructions',
      requiredFieldsHeading: 'Required fields',
    },
    toolStep: {
      viewArtifactTitle: 'Open full artifact',
      stepGenerationFailed: 'Generation failed for this step.',
    },
    artifactPreview: {
      toolbarLabel: 'Content view mode',
      panelLabel: 'Artifact content preview',
      emptyContentLabel: 'Content unavailable.',
    },
    meta: {
      phase: 'phase',
      extraction: 'extraction',
      briefing: 'briefing',
      jobDate: 'Job date',
      lastUpdate: 'Last update',
      artifactCount: 'Artifacts',
      checkpointStatus: 'checkpoint status',
      extractionContext: 'extraction context',
      toolsUploadCapability: 'tool upload capability',
      briefStatus: 'brief status',
      briefFile: 'brief file',
      nextStep: 'next step',
      streamStatus: 'stream status',
      artifact: 'artifact',
      artifactId: 'artifactId',
      sessionId: 'sessionId',
      projectId: 'projectId',
      state: 'State',
      uiState: 'UI state',
      primaryAction: 'primary action',
      requestId: 'requestId',
      reconnectAttempts: 'reconnect attempts',
      updated: 'updated',
      model: 'model',
      date: 'date',
      role: 'role',
      type: 'type',
      status: 'status',
      project: 'workspace',
    },
    states: {
      loadingProjects: 'Loading workspaces...',
      loadingDashboard: 'Loading dashboard...',
      noToolsAvailable: 'No tools available.',
      loadingUsers: 'Loading users...',
      loadingModels: 'Loading models...',
      loadingArtifact: 'Loading artifact...',
      loadingList: 'Loading...',
      noChunkReceived: 'Waiting for content...',
      disabling: 'Disabling...',
      noArtifactsFiltered: 'No artifacts available with the current filters.',
      noArtifactSelected: 'Select an artifact to see details.',
      noArtifactFound: 'Artifact not found.',
      noArtifactsAvailable: 'No artifacts available.',
      userUnavailable: 'User unavailable',
      projectUnavailable: 'Workspace unavailable',
      noProjectFound: 'Workspace not found.',
      noProjectArtifacts: 'No artifacts linked to the workspace.',
      noProjectsAvailable: 'No workspaces available.',
      toolsUploadDisabled: 'Brief upload not available in this environment.',
      artifactDeleteDisabled: 'Artifact removal not enabled.',
      extractionContextMissing: 'No brief found for the selected workspace. Upload a document to get started.',
      backendEndpointPending: 'Feature not yet available.',
      uploadingBriefing: 'Uploading...',
      extractingInformation: 'Extracting content...',
      loadingKpi: 'Loading KPIs...',
      noDataAvailable: 'No data available.',
      widgetLoadError: 'Widget load error.',
      readyForRealData: 'Ready for real data',
      noDefaultSet: 'No default set',
      emptyUsersList: 'No users available.',
      emptyModelsList: 'No models in the catalog.',
      emptyChangelogList: 'No entries published at the moment.',
      emptyUserReportsList: 'No reports found with the selected filters.',
      emptyActivityList: 'No recent activity.',
      completed: 'completed',
      pending: 'pending',
      present: 'present',
      missing: 'missing',
    },
    placeholders: {
      sourceArtifactId: 'artifact-...',
      projectId: 'project-id',
    },
    fallbackErrors: {
      loginFailed: 'Login failed',
      createProject: 'Unable to create workspace',
      loadProjects: 'Unable to load workspaces',
      loadProjectDetail: 'Unable to load workspace details',
      loadModels: 'Unable to load models',
      loadAdminModels: 'Unable to load admin models',
      loadArtifacts: 'Unable to load artifacts',
      loadSessions: 'Unable to load sessions',
      loadAdminSessions: 'Unable to load admin sessions',
      loadAdminChangelog: 'Unable to load changelog',
      loadAdminUserReports: 'Unable to load reports',
      loadAdminUsers: 'Unable to load admin users',
      loadAdminApiServices: 'Unable to load ApiService catalog',
      loadAdminApiServiceBindings: 'Unable to load ApiService bindings',
      loadArtifactDetail: 'Unable to load artifact details',
      loadAdminUsersHttp: (status: number): string => `Unable to load admin users (HTTP ${status})`,
    },
    feedback: {
      adminUsersCreated: 'User created.',
      adminUsersUpdated: 'User updated.',
      adminUsersDisabled: 'User disabled.',
      adminUsersCreateFailed: 'Unable to create user.',
      adminUsersUpdateFailed: 'Unable to update user.',
      adminUsersDisableFailed: 'Unable to disable user.',
      adminModelsCreated: 'Model created.',
      adminModelsDeleted: 'Model deleted.',
      adminModelsDefaultUpdated: 'Default model updated.',
      adminModelsStatusUpdated: 'Model status updated.',
      adminModelsCreateFailed: 'Unable to create model.',
      adminModelsDeleteFailed: 'Unable to delete model.',
      adminModelsDefaultUpdateFailed: 'Unable to update default model.',
      adminModelsStatusUpdateFailed: 'Unable to update model status.',
      projectsCreated: 'Workspace created.',
      adminChangelogPublished: 'Changelog entry published.',
      adminChangelogArchived: 'Changelog entry archived.',
      adminChangelogPublishFailed: 'Unable to publish changelog entry.',
      adminReportTriaged: 'Report triaged updated.',
      adminReportClosed: 'Report closed updated.',
      adminReportTriageFailed: 'Unable to update triage.',
      adminReportPublishIssueFailed: 'Unable to publish GitHub issue.',
      adminReportCloseFailed: 'Unable to close report.',
      adminUserReportStatusUpdated: 'Report status updated.',
      adminUserReportStatusUpdateFailed: 'Unable to update report status.',
      adminUserReportIssuePublished: 'GitHub issue published.',
      adminUserReportIssuePublishFailed: 'Unable to publish GitHub issue.',
      userReportSubmitted: 'Report submitted successfully.',
      userReportSubmitFailed: 'Unable to submit report.',
      adminApiServicesCreated: 'ApiService created.',
      adminApiServicesUpdated: 'ApiService updated.',
      adminApiServicesDeleted: 'ApiService deleted.',
      adminApiServicesCreateFailed: 'Unable to create ApiService.',
      adminApiServicesUpdateFailed: 'Unable to update ApiService.',
      adminApiServicesDeleteFailed: 'Unable to delete ApiService.',
      adminApiServiceBindingsSaved: 'ApiService binding saved.',
      adminApiServiceBindingsDeleted: 'ApiService binding deleted.',
      adminApiServiceBindingsSaveFailed: 'Unable to save ApiService binding.',
      adminApiServiceBindingsDeleteFailed: 'Unable to delete ApiService binding.',
      reportSubmitted: 'Report submitted successfully.',
      reportSubmitFailed: 'Unable to submit report.',
    },
    adminApiServices: {
      toolbarDescription: 'Administrative catalog for ApiService and bindings associated with tool steps.',
      toggleCreateHide: 'Hide form',
      toggleCreateShow: 'New ApiService',
      reloadTable: 'Refresh table',
      createFormTitle: 'New ApiService',
      createFormSubtitle: 'Configure endpoint, method, and mapping in a single view.',
      createSubmitLabel: 'Create ApiService',
      editFormTitle: 'Edit ApiService',
      editFormSubtitlePrefix: 'Update configuration for ',
      editSubmitLabel: 'Save ApiService',
      advancedJsonSummary: 'Advanced JSON',
      advancedJsonHelper: 'Optional JSON templates and mapping for advanced integration scenarios.',
      tokenHeaderNameHelper: 'Empty = Authorization (Bearer). Examples: Authorization, X-API-Key.',
      createSavingLabel: 'Saving...',
      emptyApiServices: 'No ApiService available.',
      tableHeaders: {
        key: 'Key',
        label: 'Label',
        accessMode: 'Access mode',
        requestMethod: 'Method',
        status: 'Status',
        token: 'Token',
        actions: 'Actions',
      },
      tokenConfigured: 'Configured',
      tokenNotConfigured: 'Not configured',
      openBindingsAction: 'Binding',
      bindings: {
        selectedServicePrefix: 'Selected service: ',
        noServiceSelected: 'Select an ApiService to manage bindings.',
        formLabels: {
          toolKey: 'Tool key',
          stepKey: 'Step key',
          bindingStatus: 'Binding status',
          requiredness: 'Requiredness',
          workflowStepType: 'Workflow step type',
        },
        createAction: 'Create binding',
        updateAction: 'Update binding',
        emptyForService: 'No bindings configured for this ApiService.',
      },
      fieldLabels: {
        key: 'Key',
        label: 'Label',
        baseUrl: 'Base URL',
        resourcePath: 'Resource path',
        accessMode: 'Access mode',
        requestMethod: 'Request method',
        tokenHeaderName: 'Token header name',
        timeoutMs: 'Timeout ms',
        retryCount: 'Retry count',
        contractProfileVersion: 'Contract profile version',
        status: 'Status',
        requestTemplateJson: 'Request template JSON',
        requestMappingRulesJson: 'Request mapping rules JSON',
        requestHeadersTemplateJson: 'Request headers JSON',
        responseMappingRulesJson: 'Response mapping rules JSON',
        errorMappingRulesJson: 'Error mapping rules JSON',
      },
      validation: {
        keyRequired: 'Key required',
        labelRequired: 'Label required',
        baseUrlRequired: 'Base URL required',
        resourcePathRequired: 'Resource path required',
        toolKeyRequired: 'Tool key required',
        stepKeyRequired: 'Step key required',
      },
    },
    adminUsers: {
      toolbarDescription: 'Quick provisioning, role updates, and account disabling.',
      toggleCreateHide: 'Hide form',
      toggleCreateShow: 'New user',
      reloadTable: 'Refresh table',
      createFormTitle: 'New user',
      createFormSubtitle: 'Add an account with role and initial quota.',
      createSubmitLabel: 'Create user',
      createSavingLabel: 'Creating...',
      editFormTitle: 'Edit user',
      editSubmitLabel: 'Save',
      editSavingLabel: 'Saving...',
      fieldLabels: {
        email: 'Email',
        role: 'Role',
        status: 'Status',
        monthlyQuota: 'Monthly credits',
        monthlyArtifactLimit: 'Artifact limit',
        passwordInitial: 'Initial password',
        passwordNew: 'New password',
      },
      tableHeaders: {
        email: 'Email',
        role: 'Role',
        status: 'Status',
        monthlyQuota: 'Monthly credits',
        monthlyArtifactLimit: 'Artifact limit',
        actions: 'Actions',
      },
      emptyList: 'No users available.',
    },
    adminModels: {
      toolbarDescription: 'Manage the available LLM model catalog and exposure status in the frontend selector.',
      createFormTitle: 'New model',
      createFormSubtitle: 'Add a model to the catalog.',
      createSubmitLabel: 'Create model',
      createSavingLabel: 'Creating...',
      fieldLabels: {
        key: 'Key',
        placeholderKey: 'e.g. openrouter/auto',
        label: 'Label',
        placeholderLabel: 'Display name',
        status: 'Status',
      },
      tableHeaders: {
        key: 'Key',
        label: 'Label',
        status: 'Status',
        default: 'Default',
        actions: 'Actions',
      },
      defaultLabel: 'default',
      noDefaultLabel: '-',
      emptyList: 'No models in the catalog.',
    },
    adminActivity: {
      tableHeaders: {
        project: 'Workspace',
        artifact: 'Artifact',
        status: 'Status',
        updated: 'Updated',
      },
    },
    adminChangelog: {
      toolbarDescription: 'Publish product updates visible to authenticated users.',
      createFormTitle: 'New changelog entry',
      createFormSubtitle: 'Compose title and content, then publish.',
      submitLabel: 'Publish changelog',
      savingLabel: 'Publishing...',
      fieldLabels: {
        title: 'Title',
        content: 'Content',
      },
      tableHeaders: {
        title: 'Title',
        status: 'Status',
        publishedAt: 'Published on',
        updatedAt: 'Updated on',
        actions: 'Actions',
      },
      tableTitle: 'Published entries',
      emptyList: 'No entries published at the moment.',
      toggleArchivedHide: 'Hide archived',
      toggleArchivedShow: 'Show archived',
      reloadTable: 'Refresh table',
      inboxLink: 'Reports inbox',
      archiveAction: 'Archive',
      pageDescription: 'Canonical Data Table View for published ProductChangelog and administrative archive.',
    },
    adminUserReports: {
      toolbarFilterStatusLabel: 'Status filter',
      toolbarFilterCategoryLabel: 'Category filter',
      reloadTable: 'Refresh table',
      changelogLink: 'Changelog admin',
      tableTitle: 'Reports inbox',
      tableHeaders: {
        title: 'Report',
        category: 'Category',
        status: 'Status',
        createdAt: 'Created on',
        actions: 'Actions',
      },
      triageAction: 'Triage',
      publishIssueAction: 'Publish issue',
      closeAction: 'Close',
      emptyList: 'No reports found with the selected filters.',
      pageDescription: 'Canonical Data Table View for UserReport triage and IssuePublicationPolicy.',
    },
    adminPage: {
      dataTableViewEyebrow: 'Data Table View',
    },
    adminDashboard: {
      title: 'Admin dashboard',
      openUserReportQueue: 'Open UserReport queue',
      kpi: {
        dailyQuotaUsageTitle: 'Daily quota usage',
        dailyQuotaUsageHint: 'Quota consumption trend + users at risk of saturation',
        recentAdminActivityTitle: 'Recent admin activity',
        recentAdminActivityHint: 'Critical mutations performed in the last 24h',
        operationalErrorRateTitle: 'Operational error rate',
        operationalErrorRateHint: 'Failure stream, retry dispatch, and endpoint anomalies',
        meanResolutionTimeTitle: 'Mean resolution time',
        meanResolutionTimeHint: 'Time from UserReport opening to closure/escalation',
        openUserReportsTitle: 'Open UserReports',
        openUserReportsHint: 'Issue/feature-request queue awaiting triage',
        llmCatalogStatusTitle: 'LlmModel catalog status',
        llmCatalogStatusHint: 'Enabled/disabled models and current default',
      },
      widgetPreviewLabel: 'Widget preview',
    },
    toolActions: {
      retryStepTooltip: 'Retry this step',
      retryStepLabel: 'Retry',
      skipToNextStepTooltip: 'Skip to next step',
      skipToNextStepLabel: 'Skip step',
      cancelGenerationTooltip: 'Cancel the generation in progress',
      cancelGenerationLabel: 'Cancel',
      viewPreviousResultTooltip: 'View the previous step result',
      viewPreviousResultLabel: 'Previous artifact',
    },
    toolPageForm: {
      articleTitleLabel: 'Article title',
      videoTitleLabel: 'Video title',
      topicLabel: 'Topic',
      keywordsLabel: 'Keywords (comma-separated)',
      ctaTextLabel: 'CTA text',
      ctaLinkLabel: 'CTA link',
      credentialsLabel: 'Credentials or proof',
      chaptersLabel: 'Chapters with timestamps (one per line)',
      socialLinksLabel: 'Social links (one per line)',
      hashtagsLabel: 'Hashtags (comma-separated, max 5)',
      baseQueryLabel: 'Base query',
      languageLabel: 'Language',
      selectLanguagePlaceholder: 'Select language',
      countryDomainLabel: 'Country / Google Domain',
      selectDomainPlaceholder: 'Select domain',
      brandNameLabel: 'Brand name (optional)',
      languageOptionIt: 'Italian (it)',
      languageOptionEn: 'English (en)',
      languageOptionEs: 'Spanish (es)',
      languageOptionFr: 'French (fr)',
      languageOptionDe: 'German (de)',
      domainOptionGoogleIt: 'google.it (Italy)',
      domainOptionGoogleCom: 'google.com (Global)',
      domainOptionGoogleEs: 'google.es (Spain)',
      domainOptionGoogleFr: 'google.fr (France)',
      domainOptionGoogleDe: 'google.de (Germany)',
      domainOptionGoogleCoUk: 'google.co.uk (UK)',
    },
    adminNavigation: {
      ariaLabel: 'Administration navigation',
      overviewLabel: 'Overview',
      overviewDescription: 'Central dashboard for administrative workflows.',
      sessionsLabel: 'Sessions',
      sessionsDescription: 'All user sessions and production output.',
      usersLabel: 'Users',
      usersDescription: 'Provisioning, roles, account status, monthly credits, and artifact limit.',
      modelsLabel: 'LLM models',
      modelsDescription: 'LlmModel catalog and availability status.',
      apiServicesLabel: 'ApiService',
      apiServicesDescription: 'ApiService catalog and tool step bindings.',
      changelogLabel: 'Changelog',
      changelogDescription: 'ProductChangelog publishing and archive.',
      userReportsLabel: 'Reports',
      userReportsDescription: 'UserReport inbox and escalation policy.',
      activityLabel: 'Recent activity',
      activityDescription: 'Tabular view of recent workspace checkpoints.',
      openAdminLink: 'Open admin',
    },
    feedbackCenter: {
      newsHeading: 'News',
      newsSubheading: 'Changelog published by admins.',
      formHeading: 'Report an issue',
      formSubheading: 'Help us improve the platform.',
      closeFormAriaLabel: 'Close feedback form',
      closeFormTitle: 'Close form',
      loadingChangelog: 'Loading changelog...',
      noNewsAvailable: 'No news published at the moment.',
      unavailableDate: 'Date unavailable',
      submitButtonText: 'Submit report',
      submitButtonLoading: 'Submitting...',
      submitButtonSubmit: 'Submit',
      backToFormText: 'Back to form',
      formCategoryLabel: 'Category',
      formTitleLabel: 'Title',
      formDescriptionLabel: 'Description',
      formValidationError: 'Title and description are required.',
      openNewsAriaLabel: 'Open news',
      closeNewsAriaLabel: 'Close news',
    },
    feedbackCenterOptions: {
      categories: [
        { value: 'issue', label: 'Bug' },
        { value: 'feature-request', label: 'Feature request' },
        { value: 'other', label: 'Other' },
      ] satisfies ReadonlyArray<CopyOption<'issue' | 'feature-request' | 'other'>>,
    },
    feedbackButtons: {
      alreadyVotedPositive: 'Already voted positive',
      goodExample: 'Good example',
      alreadyVotedNegative: 'Already voted negative',
      poorExample: 'Poor example',
      votePositiveAria: 'Positive vote',
      voteNegativeAria: 'Negative vote',
    },
    options: {
      intent: [
        { value: 'new', label: 'New' },
        { value: 'resume', label: 'Resume' },
        { value: 'regenerate', label: 'Regenerate' },
      ] satisfies ReadonlyArray<CopyOption<'new' | 'resume' | 'regenerate'>>,
      artifactTypes: [
        { value: 'all', label: 'All' },
        { value: 'content', label: 'Content' },
        { value: 'seo', label: 'SEO' },
        { value: 'code', label: 'Code' },
        { value: 'extraction', label: 'Extraction' },
      ] satisfies ReadonlyArray<CopyOption<'all' | 'content' | 'seo' | 'code' | 'extraction'>>,
      artifactStatuses: [
        { value: 'all', label: 'All' },
        { value: 'generating', label: 'In progress' },
        { value: 'completed', label: 'Completed' },
        { value: 'failed', label: 'Failed' },
      ] satisfies ReadonlyArray<CopyOption<'all' | 'generating' | 'completed' | 'failed'>>,
      artifactPeriods: [
        { value: 'all', label: 'all' },
        { value: '7d', label: '7d' },
        { value: '30d', label: '30d' },
        { value: '90d', label: '90d' },
      ] satisfies ReadonlyArray<CopyOption<'all' | '7d' | '30d' | '90d'>>,
      outputFormats: [
        { value: 'plain', label: 'Plain text' },
        { value: 'json', label: 'JSON' },
        { value: 'markdown', label: 'Markdown' },
      ] satisfies ReadonlyArray<CopyOption<'plain' | 'json' | 'markdown'>>,
    },
    workspace: {
      contextHeader: {
        breadcrumbWorkspaces: 'Workspaces',
        assetCountLabel: 'assets available',
        suggestedNextLabel: 'Next:',
        emptyTools: 'No tools available.',
        actionNeeded: 'Action needed',
        ready: 'Ready',
        qualityGateReady: 'Ready',
        qualityGateNeedsReview: 'Needs Review',
        qualityGateBlocked: 'Blocked',
        qualityLabel: 'quality',
        noQuality: 'No quality',
        archivedBadge: 'Archived',
        archiveAlertMessage: 'This workspace is archived. Content is read-only until reactivated.',
        reactivateAction: 'Reactivate',
        reactivateAriaLabel: 'Reactivate workspace',
        archiveAriaLabel: 'Archive workspace',
        archiveSuccess: 'Workspace archived.',
        reactivateSuccess: 'Workspace reactivated.',
        archiveFailed: 'Failed to update workspace status.',
        unableToLoadData: 'Unable to load workspace data',
      },
      sectionNav: {
        label: 'Workspace sections',
        overview: 'Overview',
        assets: 'Library',
        sessions: 'Sessions',
      },
      dashboard: {
        title: 'Workspace Dashboard',
        availableToolsTitle: 'Available Tools',
        assetLibraryTitle: 'Asset Library',
        loadingAssets: 'Loading assets…',
        loadingWorkspace: 'Loading workspace...',
        loadingActivity: 'Loading activity...',
        recentActivityTitle: 'Recent Activity',
        recentSessionsTitle: 'Recent Sessions',
        recentSessionsEmpty: 'No sessions yet. Run a tool to generate content.',
        recentArtifactsTitle: 'Recent Artifacts',
        recentArtifactsEmpty: 'No recent artifacts. Run a tool to generate content.',
        recentArtifactsNoContent: '(no content)',
        recentArtifactsPromotedChip: 'Asset ✓',
        recentArtifactsPromoteAction: 'Promote to Asset',
        recentAssetsTitle: 'Recent Assets',
        recentAssetsEmpty: 'No assets yet — start by using a tool.',
        foundationToolsTitle: 'Foundation',
        foundationToolsRegenerate: 'Regenerate',
        foundationStatusMissing: 'Missing',
        foundationStatusPresent: (count: number) => `${count} asset${count === 1 ? '' : 's'}`,
        foundationActionGenerate: 'Generate',
        foundationTooltipBrief: 'Generate new Brief',
        foundationTooltipTov: 'Generate new Brand Voice',
        foundationTooltipPersonas: 'Generate new Personas',
        foundationLabelBrief: 'Brief',
        foundationLabelBrandVoice: 'Brand Voice',
        foundationLabelPersonas: 'Personas',
        heroStartGenerating: 'Start generating',
        heroChooseTool: 'Choose a tool',
        heroSuggestionsReady: (count: number) => `${count} tool suggestion${count > 1 ? 's' : ''} ready`,
        heroAssetsReady: (count: number) => `${count} asset${count > 1 ? 's' : ''} · select a tool to continue`,
        heroFirstAsset: 'Start by creating your first asset',
        workspaceOverviewQuality: (score: number) => `${score}% quality`,
        workspaceOverviewStatsAssets: (count: number) => `${count} asset${count === 1 ? '' : 's'}`,
        workspaceOverviewStatsTypes: (count: number) => `${count} type${count === 1 ? '' : 's'}`,
        workspaceOverviewStatsStale: (count: number) => `${count} stale`,
        workspaceOverviewStatsNone: 'No assets yet',
        workspaceOverviewFoundationLabel: 'Foundation Assets',
        viewAllSessions: 'View all sessions',
        viewAllSessionsArrow: 'View all sessions',
        viewAllAssetsArrow: 'View all assets',
        lastActivity: 'Last activity',
        loadingGeneric: 'Loading...',
        noSessionsYet: 'No sessions yet',
        noSessionsStartTool: 'No sessions yet \u2014 start by selecting a tool.',
        workspaceSubtitle: (count: number) => `${count} workspace${count === 1 ? '' : 's'} available`,
        workspaceSessions: 'Workspace Sessions',
        artifactCountLabel: (count: number) => `${count} artifact${count === 1 ? '' : 's'}`,
      },
      assetPanel: {
        title: 'Workspace Knowledge',
        metricsAssets: 'assets',
        metricsQuality: 'quality',
        groupRequiredLabel: 'Required',
        groupOptionalLabel: 'Optional',
        groupMissingRequired: 'Missing (Required)',
        groupMissingOptional: 'Missing (Optional)',
        selectedCount: 'selected',
        generateMoreAction: 'Generate More',
        createAssetAction: 'Create',
        staleLabel: 'Stale',
        selectAll: 'Select All',
        deselectAll: 'Deselect All',
        collapseGroup: 'Collapse group',
        expandGroup: 'Expand group',
        percentReady: (score: number) => `${score}% ready`,
        selectedForGeneration: (count: number) => `${count} asset${count === 1 ? '' : 's'} selected for generation`,
      },
      createAsset: {
        failedCreate: 'Failed to create asset',
        failedUpload: 'Failed to upload file',
        nameLabel: (label: string) => `${label} name`,
        namePlaceholder: (label: string) => `My ${label}`,
        contentLabel: 'Content (optional)',
        contentPlaceholder: (label: string) => `Paste or type ${label.toLowerCase()} content...`,
        creating: 'Creating...',
        createAsset: 'Create asset',
        cancel: 'Cancel',
        requiredHint: (label: string) => `${label} assets are required for optimal generation.`,
        optionalHint: (label: string) => `${label} assets would improve generation quality.`,
        generateWith: (tool: string) => `Generate with ${tool}`,
        uploading: 'Uploading...',
        uploadFile: 'Upload file',
        pasteText: 'Paste text',
      },
      createDialog: {
        title: 'Create New Workspace',
        nameLabel: 'Workspace Name',
        descriptionLabel: 'Description (optional)',
        nameRequired: 'Name is required',
        failedCreate: 'Failed to create workspace',
        creating: 'Creating...',
        create: 'Create',
      },
    },
    promoteDialog: {
      title: 'Promote to Asset',
      successMessage: 'Asset created successfully! Available in the workspace.',
      description: 'Convert this generated artifact into a reusable asset in your workspace.',
      labelField: 'Label',
      labelHelper: 'A descriptive name for this asset',
      close: 'Close',
      cancel: 'Cancel',
      promoting: 'Promoting...',
      promote: 'Promote',
      failedPromote: 'Failed to promote artifact',
    },
    dashboard: {
      foundationSummaryTitle: 'Foundation across workspaces',
      foundationSummaryFraction: (present: number, total: number) => `${present}/${total} workspaces`,
      foundationSummaryFooterLink: 'Complete Foundation',
      recommendedActionsTitle: 'Recommended next actions',
      recommendedActionsEmpty: 'All caught up \u2014 every recent workspace has what it needs.',
      recommendedActionUseLabel: 'Use',
      recommendedActionWorkspaceLabel: (name: string) => `in ${name}`,
      activeWorkspacesTitle: 'Your workspaces',
      activeWorkspacesFooterLink: 'View all workspaces',
    },
    toolWorkflowJob: {
      status: {
        queued: 'Queued',
        running: 'Running',
        completed: 'Completed',
        failed: 'Failed',
        cancelled: 'Cancelled',
      },
      stepTracker: {
        idle: 'Waiting',
        running: 'Generating...',
        done: 'Completed',
        error: 'Error',
      },
      cancel: {
        label: 'Cancel',
        confirming: 'Cancelling...',
        success: 'Job cancelled',
      },
      stream: {
        connectionLost: 'Connection lost. Reconnecting...',
        reconnected: 'Reconnected',
      },
      admin: {
        pageTitle: 'Tool Jobs',
        tableJobId: 'Job ID',
        tableStatus: 'Status',
        tableTool: 'Tool',
        tableProject: 'Project',
        tableUser: 'User',
        tableProgress: 'Progress',
        tableCreated: 'Created',
        actionInspect: 'Inspect',
        actionCancel: 'Cancel',
        actionRetry: 'Retry',
        toolbarDescription: 'Manage and monitor ToolWorkflowJobs across all users.',
        reloadTable: 'Refresh',
        emptyList: 'No tool jobs found.',
        filterStatus: 'Status',
        filterTool: 'Tool',
        filterAll: 'All',
      },
    },
  },
  editorial: {
    publicShell: {
      eyebrow: 'Campaign orchestration for digital teams',
      headline: 'A production workspace for concepts, funnels, and artifacts that must convince at first glance.',
      body: 'Designed for marketing teams aged 25-35 working across positioning, landing pages, creative sprints, and continuous revisions: less operational friction, more editorial rhythm.',
    },
    auth: {
      eyebrow: 'Private client area',
      headline: 'Sign in to the control room.',
      body: 'Find your projects, guided tools, and artifacts ready for copy review, delivery, or team handoff.',
      pendingAccess: 'Signing in...',
    },
    header: {
      headline: 'Stratego Flow',
    },
    dashboard: {
      eyebrow: 'Welcome back',
      heroHeadlineResume: (toolLabel: string) => `Continue with ${toolLabel}`,
      heroHeadlineChoose: 'Choose a workspace to continue',
      heroSubtitleResume: (workspaceName: string) => `Pick up where you left off in ${workspaceName}.`,
      heroSubtitleChoose: 'Select a workspace to start generating or complete its Foundation.',
      heroCtaResume: (toolLabel: string) => `Resume ${toolLabel}`,
      heroCtaChoose: 'Choose a workspace',
      recentActivityTitle: 'Recent activity',
      zeroState: {
        eyebrow: 'Welcome',
        headline: 'Everything starts with a workspace.',
        body: 'A workspace is the context where you organize briefs, generations, and output. Create one now to start working with generation tools.',
        cta: 'Create your first workspace',
      },
    },
    projects: {
      listTitle: 'Workspaces',
      detailTitle: 'Workspace detail',
      newTitle: 'New workspace',
      contextualArtifacts: 'Contextual artifacts',
      contextualSessions: 'Contextual sessions',
    },
    artifacts: {
      archiveTitle: 'Artifacts archive',
      detailTitle: 'Artifact detail',
    },
    sessions: {
      archiveTitle: 'Session archive',
      detailTitle: 'Session detail',
      loadingState: 'Loading session...',
      notFound: 'Session not found.',
      emptyState: 'No sessions available.',
      emptyStateProject: 'No sessions linked to the project.',
      artifactCountLabel: 'artifact',
    },
    admin: {
      activityTitle: 'Recent activity',
      activityBody: 'Recent workspace activity.',
      sessionsTitle: 'All sessions',
      sessionsBody: 'All user sessions and production output.',
      modelsTitle: 'Admin models',
      usersTitle: 'Admin users',
      changelogTitle: 'Admin changelog',
      userReportsTitle: 'Admin user reports',
      apiServicesTitle: 'Admin ApiService',
      apiServicesBody: 'Administrative catalog for ApiService and tool step bindings.',
      apiServiceBindingsTitle: 'ApiService bindings',
    },
    feedback: {
      userReportTitle: 'User report submission',
      userReportSubmitButton: 'Submit report',
      userReportSuccessMessage: 'Report submitted successfully.',
      userReportBackToForm: 'Back to form',
    },
    generation: {
      setupTitle: 'Configure generation',
      streamTitle: 'Generated content',
      historyTitle: 'Artifact history',
      artifactDetailTitle: 'Artifact detail',
      defaultPrompt: 'Write a concise landing page in a direct style.',
      defaultTone: 'direct',
    },
    tools: {
      funnelPages: {
        title: 'Hotlead Funnel Tool',
        orderRule: 'Mandatory step order: optin -> quiz -> vsl',
        defaultPrompt: 'Generate the requested Funnel step consistent with the extracted brief.',
      },
      nextland: {
        title: 'Nextland Tool',
        orderRule: 'Mandatory step order: landing -> thank_you',
        defaultPrompt: 'Generate the requested Nextland step consistent with the extracted brief.',
      },
      youtubeLfScript: {
        title: 'YouTube LF Script Tool',
        orderRule: 'Mandatory step order: pre-script-analysis -> packaging -> intro-structure -> body-structure -> native-cta-embeds -> outro-structure',
        defaultPrompt: 'Generate the requested YouTube LF Script step consistent with the extracted brief.',
      },
      angleGenerator: {
        title: 'Angle Generator Tool',
        orderRule: 'Mandatory step order: context-and-angle-matrix -> angle-prioritization -> creative-activation',
        defaultPrompt: 'Generate prioritized angles and creative activations consistent with the extracted context.',
      },
      metaAds: {
        title: 'MetaAds Generator Tool',
        orderRule: 'Mandatory step order: context-generation -> ads-generation',
        defaultPrompt: 'Generate high-conversion Meta Ads copy consistent with the extracted context.',
      },
      youtubeDescription: {
        title: 'YT Description Generator Tool',
        orderRule: 'Mandatory step order: youtube-description-generation',
        defaultPrompt: 'Generate a complete YouTube description with CTA, chapters, and hashtags.',
      },
      geometric: {
        title: 'Geometric Tool',
        orderRule: 'Mandatory step order: serp-crawling -> competitor-scoring -> strategic-reporting -> unified-report',
        defaultPrompt: 'Analyze the SERP landscape, competitive scoring, and generate a strategic report and a unified report.',
      },
    },
  },
} as const;
