type CopyOption<T extends string> = {
  value: T;
  label: string;
};

export const formatMeta = (label: string, value: string | number): string => `${label}: ${value}`;

export const appCopy = {
  ui: {
    session: {
      verifying: 'Verifica sessione...',
      unavailable: 'Sessione non disponibile.',
    },
    badges: {
      runtimeAsIs: 'workspace attivo',
    },
    navigation: {
      dashboard: 'Dashboard',
      projects: 'Projects',
      funnelPages: 'Funnel Pages',
      nextland: 'Nextland',
      artifacts: 'Artifacts',
      admin: 'Admin',
    },
    actions: {
      logout: 'Esci',
      switchToDarkTheme: 'Attiva tema scuro',
      switchToLightTheme: 'Attiva tema chiaro',
      continueWithGoogleWorkspace: 'Continua con Google Workspace',
      enterWorkspace: 'Entra nel workspace',
      openProjects: 'Apri projects',
      openArchive: "Torna all'archivio",
      backToList: 'Torna alla lista',
      openDetail: 'Apri dettaglio',
      openArtifact: 'Apri artifact',
      openContextProject: 'Apri progetto di contesto',
      newProject: 'Nuovo progetto',
      createProject: 'Crea progetto',
      retry: 'Riprova',
      cancel: 'Cancella',
      reset: 'Ricomincia',
      processBriefing: 'Processa briefing',
      processBrief: 'Processa brief',
      startGeneration: 'Avvia la generazione',
      runNextStep: 'Avvia step successivo',
      useCheckpointResume: 'Riprendi da dove eri rimasto',
      useCheckpointRegenerate: 'Rigenera con nuovi parametri',
      historyBack: 'Torna allo storico',
      relaunchPrimary: 'Avvia di nuovo',
      deleteUiOnly: 'Rimuovi dalla vista',
      copyContent: 'Copia contenuto',
      copied: 'Copiato!',
      copyFailed: 'Copia fallita',
      viewMarkdown: 'Markdown',
      viewRaw: 'Raw',
    },
    labels: {
      email: 'Email',
      password: 'Password',
      themeLight: 'Tema chiaro',
      themeDark: 'Tema scuro',
      intent: 'Tipo di operazione',
      checkpointAvailable: 'Usa punto di ripresa',
      recentCheckpoint: 'Punto di ripresa disponibile',
      sourceArtifactId: 'Artefatto di partenza',
      projectId: 'Project ID',
      projectName: 'Nome progetto',
      projectDescription: 'Descrizione',
      briefingFile: 'Briefing file (.docx, .txt, .md)',
      briefFile: 'Brief file (.docx, .txt, .md)',
      artifactType: 'Tipo di contenuto',
      model: 'Modello AI',
      toneOptional: 'Tono (opzionale)',
      notesOptional: 'Note aggiuntive (opzionale)',
      prompt: 'Prompt',
      promptFallback: 'Prompt di riserva',
      outputFormat: 'Formato di output',
      workflowType: 'Tipo di flusso',
      toolKey: 'Tool',
      idempotencyKey: 'Chiave di idempotenza',
      registrySnapshotRef: 'Versione di riferimento',
      type: 'Tipo',
      status: 'Stato',
      project: 'Progetto',
      period: 'Periodo',
    },
    meta: {
      phase: 'phase',
      extraction: 'extraction',
      briefing: 'briefing',
      checkpointStatus: 'checkpoint status',
      extractionContext: 'extraction context',
      toolsUploadCapability: 'toolsUpload capability',
      briefStatus: 'brief status',
      briefFile: 'brief file',
      nextStep: 'next step',
      streamStatus: 'stream status',
      artifact: 'artifact',
      artifactId: 'artifactId',
      projectId: 'projectId',
      state: 'Stato',
      uiState: 'uiState',
      primaryAction: 'primaryAction',
      requestId: 'requestId',
      reconnectAttempts: 'reconnect attempts',
      updated: 'updated',
      model: 'model',
      date: 'date',
      role: 'role',
      type: 'type',
      status: 'status',
      project: 'project',
    },
    states: {
      loadingProjects: 'Caricamento progetti...',
      noChunkReceived: 'In attesa del contenuto...',
      noArtifactsFiltered: 'Nessun artefatto disponibile con i filtri correnti.',
      noArtifactSelected: 'Seleziona un artefatto per vedere il dettaglio.',
      noArtifactFound: 'Artefatto non trovato.',
      noArtifactsAvailable: 'Nessun artefatto disponibile.',
      noProjectFound: 'Progetto non trovato.',
      noProjectArtifacts: 'Nessun artefatto collegato al progetto.',
      noProjectsAvailable: 'Nessun progetto disponibile.',
      toolsUploadDisabled: 'Caricamento brief non disponibile in questo ambiente.',
      artifactDeleteDisabled: 'Rimozione artefatti non abilitata.',
      extractionContextMissing: 'Nessun brief trovato per il progetto selezionato. Carica un documento per iniziare.',
      backendEndpointPending: 'Funzionalità non ancora disponibile.',
      uploadingBriefing: 'Caricamento in corso...',
      extractingInformation: 'Estrazione contenuto in corso...',
      completed: 'completed',
      pending: 'pending',
      present: 'present',
      missing: 'missing',
    },
    placeholders: {
      sourceArtifactId: 'artifact-...',
      projectId: 'project-id',
    },
    fallbackErrors: {
      loginFailed: 'Login failed',
      createProject: 'Unable to create project',
      loadProjects: 'Unable to load projects',
      loadAdminUsers: 'Admin users load failed',
      loadAdminUsersHttp: (status: number): string => `Unable to load admin users (HTTP ${status})`,
    },
    options: {
      intent: [
        { value: 'new', label: 'Nuovo' },
        { value: 'resume', label: 'Riprendi' },
        { value: 'regenerate', label: 'Rigenera' },
      ] satisfies ReadonlyArray<CopyOption<'new' | 'resume' | 'regenerate'>>,
      artifactTypes: [
        { value: 'all', label: 'Tutti' },
        { value: 'content', label: 'Contenuto' },
        { value: 'seo', label: 'SEO' },
        { value: 'code', label: 'Codice' },
        { value: 'extraction', label: 'Estrazione' },
      ] satisfies ReadonlyArray<CopyOption<'all' | 'content' | 'seo' | 'code' | 'extraction'>>,
      artifactStatuses: [
        { value: 'all', label: 'Tutti' },
        { value: 'generating', label: 'In corso' },
        { value: 'completed', label: 'Completati' },
        { value: 'failed', label: 'Con errore' },
      ] satisfies ReadonlyArray<CopyOption<'all' | 'generating' | 'completed' | 'failed'>>,
      artifactPeriods: [
        { value: 'all', label: 'all' },
        { value: '7d', label: '7d' },
        { value: '30d', label: '30d' },
        { value: '90d', label: '90d' },
      ] satisfies ReadonlyArray<CopyOption<'all' | '7d' | '30d' | '90d'>>,
      outputFormats: [
        { value: 'plain', label: 'Testo semplice' },
        { value: 'json', label: 'JSON' },
        { value: 'markdown', label: 'Markdown' },
      ] satisfies ReadonlyArray<CopyOption<'plain' | 'json' | 'markdown'>>,
    },
  },
  editorial: {
    publicShell: {
      eyebrow: 'Campaign orchestration for digital teams',
      headline: 'Un workspace di produzione per concept, funnel e artifact che devono convincere al primo sguardo.',
      body: 'Pensato per team marketing 25-35 che lavorano tra posizionamento, landing, sprint creativi e revisioni continue: meno frizione operativa, piu ritmo editoriale.',
    },
    auth: {
      eyebrow: 'Private client area',
      headline: 'Accedi alla control room.',
      body: 'Ritrova progetti, tool guidati e artifact pronti per copy review, consegna o handoff al team.',
      pendingAccess: 'Accesso in corso...',
    },
    header: {
      eyebrow: 'Editorial growth cockpit',
      headline: 'Campaign Operating System',
    },
    dashboard: {
      eyebrow: 'Overview',
      headline: 'Ogni sprint creativo, ordinato come un newsroom board.',
      body: 'Monitora la pipeline di produzione, passa da un tool all\'altro e tieni vicini gli artifact che servono davvero alla prossima review.',
      stats: [
        'artefatti nel workspace',
        'tool disponibili per la generazione',
        'artefatti completati con successo',
      ],
      cards: {
        projects: {
          title: 'Projects',
          body: 'Apri i contesti attivi, prepara nuovi brief e mantieni allineati team, target e deliverable.',
        },
        tools: {
          title: 'Tools',
          body: 'Dai forma a funnel e pagine con flussi guidati pensati per produzione rapida e handoff pulito.',
        },
        recentArtifacts: {
          title: 'Recent Artifacts',
        },
      },
    },
    projects: {
      listTitle: 'Projects',
      detailTitle: 'Project detail',
      newTitle: 'Nuovo progetto',
      contextualArtifacts: 'Artifacts contestuali',
    },
    artifacts: {
      archiveTitle: 'Artifacts archive',
      detailTitle: 'Artifact detail',
    },
    admin: {
      activityTitle: 'Attività recente',
      activityBody: 'Attività recente del workspace.',
      modelsTitle: 'Admin models',
      usersTitle: 'Admin users',
    },
    generation: {
      setupTitle: 'Configura la generazione',
      streamTitle: 'Contenuto generato',
      historyTitle: 'Storico artefatti',
      artifactDetailTitle: 'Dettaglio artifact',
      defaultPrompt: 'Scrivi una landing page sintetica in stile diretto.',
      defaultTone: 'diretto',
    },
    tools: {
      funnelPages: {
        title: 'Funnel Pages Tool',
        orderRule: 'Ordine step obbligatorio: optin -> quiz -> vsl',
        defaultPrompt: 'Genera lo step Funnel richiesto con coerenza al brief estratto.',
      },
      nextland: {
        title: 'Nextland Tool',
        orderRule: 'Ordine step obbligatorio: landing -> thank_you',
        defaultPrompt: 'Genera lo step Nextland richiesto con coerenza al brief estratto.',
      },
    },
  },
} as const;

export const appNavigation = [
  { to: '/dashboard', label: appCopy.ui.navigation.dashboard, end: true },
  { to: '/dashboard/projects', label: appCopy.ui.navigation.projects, end: true },
  { to: '/tools/funnel-pages', label: appCopy.ui.navigation.funnelPages, end: false },
  { to: '/tools/nextland', label: appCopy.ui.navigation.nextland, end: false },
  { to: '/artifacts', label: appCopy.ui.navigation.artifacts, end: false },
  { to: '/admin', label: appCopy.ui.navigation.admin, end: false },
] as const;