type CopyOption<T extends string> = {
  value: T;
  label: string;
};

export const formatMeta = (label: string, value: string | number): string => `${label}: ${value}`;

export const appCopy = {
  ui: {
    session: {
      verifying: 'Verifica sessione...',
      unavailable: 'Sessione non disponibile.',
    },
    badges: {
      runtimeAsIs: 'runtime: as-is',
    },
    navigation: {
      dashboard: 'Dashboard',
      projects: 'Projects',
      funnelPages: 'Funnel Pages',
      nextland: 'Nextland',
      artifacts: 'Artifacts',
      admin: 'Admin',
    },
    actions: {
      logout: 'Esci',
      continueWithGoogleWorkspace: 'Continua con Google Workspace',
      enterWorkspace: 'Entra nel workspace',
      openProjects: 'Apri projects',
      openArchive: "Torna all'archivio",
      backToList: 'Torna alla lista',
      openDetail: 'Apri dettaglio',
      openArtifact: 'Apri artifact',
      openContextProject: 'Apri progetto di contesto',
      newProject: 'Nuovo progetto',
      createProject: 'Crea progetto',
      retry: 'Riprova',
      cancel: 'Cancella',
      reset: 'Reset',
      processBriefing: 'Processa briefing',
      processBrief: 'Processa brief',
      startGeneration: 'Avvia generazione',
      runNextStep: 'Esegui prossimo step reale',
      useCheckpointResume: 'Usa checkpoint per resume',
      useCheckpointRegenerate: 'Usa checkpoint per regenerate',
      historyBack: 'Torna allo storico',
      relaunchPrimary: 'Relaunch primario',
      relaunchSecondary: 'Relaunch secondario',
      deleteUiOnly: 'Delete (UI only)',
    },
    labels: {
      email: 'Email',
      password: 'Password',
      intent: 'Intent',
      checkpointAvailable: 'Checkpoint disponibile',
      recentCheckpoint: 'Checkpoint recente (progetto)',
      sourceArtifactId: 'Source artifact ID',
      projectId: 'Project ID',
      projectName: 'Nome progetto',
      projectDescription: 'Descrizione',
      briefingFile: 'Briefing file (.docx, .txt, .md)',
      briefFile: 'Brief file (.docx, .txt, .md)',
      artifactType: 'Artifact type',
      model: 'Model',
      toneOptional: 'Tone (optional)',
      notesOptional: 'Notes (optional)',
      prompt: 'Prompt',
      promptFallback: 'Prompt fallback',
      outputFormat: 'Output format',
      workflowType: 'Workflow type',
      toolKey: 'Tool key',
      idempotencyKey: 'Idempotency key',
      registrySnapshotRef: 'Registry snapshot ref',
      type: 'Tipo',
      status: 'Stato',
      project: 'Progetto',
      period: 'Periodo',
    },
    meta: {
      phase: 'phase',
      extraction: 'extraction',
      briefing: 'briefing',
      checkpointStatus: 'checkpoint status',
      extractionContext: 'extraction context',
      toolsUploadCapability: 'toolsUpload capability',
      briefStatus: 'brief status',
      briefFile: 'brief file',
      nextStep: 'next step',
      streamStatus: 'stream status',
      artifact: 'artifact',
      artifactId: 'artifactId',
      projectId: 'projectId',
      state: 'Stato',
      uiState: 'uiState',
      primaryAction: 'primaryAction',
      requestId: 'requestId',
      reconnectAttempts: 'reconnect attempts',
      updated: 'updated',
      model: 'model',
      date: 'date',
      role: 'role',
      type: 'type',
      status: 'status',
      project: 'project',
    },
    states: {
      loadingProjects: 'Caricamento progetti...',
      noChunkReceived: 'Nessun chunk ricevuto',
      noArtifactsFiltered: 'Nessun artifact disponibile con i filtri correnti.',
      noArtifactSelected: 'Seleziona un artifact per vedere il dettaglio.',
      noArtifactFound: 'Artifact non trovato.',
      noArtifactsAvailable: 'Nessun artifact disponibile.',
      noProjectFound: 'Progetto non trovato.',
      noProjectArtifacts: 'Nessun artifact collegato al progetto.',
      noProjectsAvailable: 'Nessun progetto disponibile.',
      toolsUploadDisabled: 'toolsUpload capability: disabled',
      artifactDeleteDisabled: 'ARTIFACT_DELETE_ENABLED=false',
      extractionContextMissing: 'Extraction context mancante per il progetto selezionato. Carica e processa un brief.',
      backendEndpointPending: 'Backend endpoint pending',
      uploadingBriefing: 'Uploading briefing...',
      extractingInformation: 'Extracting information...',
      completed: 'completed',
      pending: 'pending',
      present: 'present',
      missing: 'missing',
    },
    placeholders: {
      sourceArtifactId: 'artifact-...',
      projectId: 'project-id',
    },
    fallbackErrors: {
      loginFailed: 'Login failed',
      createProject: 'Unable to create project',
      loadProjects: 'Unable to load projects',
      loadAdminUsers: 'Admin users load failed',
      loadAdminUsersHttp: (status: number): string => `Unable to load admin users (HTTP ${status})`,
    },
    options: {
      intent: [
        { value: 'new', label: 'new' },
        { value: 'resume', label: 'resume' },
        { value: 'regenerate', label: 'regenerate' },
      ] satisfies ReadonlyArray<CopyOption<'new' | 'resume' | 'regenerate'>>,
      artifactTypes: [
        { value: 'all', label: 'all' },
        { value: 'content', label: 'content' },
        { value: 'seo', label: 'seo' },
        { value: 'code', label: 'code' },
        { value: 'extraction', label: 'extraction' },
      ] satisfies ReadonlyArray<CopyOption<'all' | 'content' | 'seo' | 'code' | 'extraction'>>,
      artifactStatuses: [
        { value: 'all', label: 'all' },
        { value: 'generating', label: 'generating' },
        { value: 'completed', label: 'completed' },
        { value: 'failed', label: 'failed' },
      ] satisfies ReadonlyArray<CopyOption<'all' | 'generating' | 'completed' | 'failed'>>,
      artifactPeriods: [
        { value: 'all', label: 'all' },
        { value: '7d', label: '7d' },
        { value: '30d', label: '30d' },
        { value: '90d', label: '90d' },
      ] satisfies ReadonlyArray<CopyOption<'all' | '7d' | '30d' | '90d'>>,
      outputFormats: [
        { value: 'plain', label: 'plain' },
        { value: 'json', label: 'json' },
        { value: 'markdown', label: 'markdown' },
      ] satisfies ReadonlyArray<CopyOption<'plain' | 'json' | 'markdown'>>,
    },
  },
  editorial: {
    publicShell: {
      eyebrow: 'Campaign orchestration for digital teams',
      headline: 'Un workspace di produzione per concept, funnel e artifact che devono convincere al primo sguardo.',
      body: 'Pensato per team marketing 25-35 che lavorano tra posizionamento, landing, sprint creativi e revisioni continue: meno frizione operativa, piu ritmo editoriale.',
    },
    auth: {
      eyebrow: 'Private client area',
      headline: 'Accedi alla control room.',
      body: 'Ritrova progetti, tool guidati e artifact pronti per copy review, consegna o handoff al team.',
      pendingAccess: 'Accesso in corso...',
    },
    header: {
      eyebrow: 'Editorial growth cockpit',
      headline: 'Campaign Operating System',
    },
    dashboard: {
      eyebrow: 'Overview',
      headline: 'Ogni sprint creativo, ordinato come un newsroom board.',
      body: 'Monitora la pipeline di produzione, passa da un tool all\'altro e tieni vicini gli artifact che servono davvero alla prossima review.',
      stats: [
        'artifact tracciati nel workspace',
        'percorsi guidati attivi per la generazione',
        'runtime pronto per review continue e fallback locale',
      ],
      cards: {
        projects: {
          title: 'Projects',
          body: 'Apri i contesti attivi, prepara nuovi brief e mantieni allineati team, target e deliverable.',
        },
        tools: {
          title: 'Tools',
          body: 'Dai forma a funnel e pagine con flussi guidati pensati per produzione rapida e handoff pulito.',
        },
        recentArtifacts: {
          title: 'Recent Artifacts',
        },
      },
    },
    projects: {
      listTitle: 'Projects',
      detailTitle: 'Project detail',
      newTitle: 'Nuovo progetto',
      contextualArtifacts: 'Artifacts contestuali',
    },
    artifacts: {
      archiveTitle: 'Artifacts archive',
      detailTitle: 'Artifact detail',
    },
    admin: {
      activityTitle: 'Admin activity',
      activityBody: 'Feed locale derivato da checkpoint/artifacts (fallback).',
      modelsTitle: 'Admin models',
      usersTitle: 'Admin users',
    },
    generation: {
      setupTitle: 'Tool setup comune',
      streamTitle: 'Stream output',
      historyTitle: 'Storico artefatti',
      artifactDetailTitle: 'Dettaglio artifact',
      defaultPrompt: 'Scrivi una landing page sintetica in stile diretto.',
      defaultTone: 'diretto',
    },
    tools: {
      funnelPages: {
        title: 'Funnel Pages Tool',
        orderRule: 'Ordine step obbligatorio: optin -> quiz -> vsl',
        defaultPrompt: 'Genera lo step Funnel richiesto con coerenza al brief estratto.',
      },
      nextland: {
        title: 'Nextland Tool',
        orderRule: 'Ordine step obbligatorio: landing -> thank_you',
        defaultPrompt: 'Genera lo step Nextland richiesto con coerenza al brief estratto.',
      },
    },
  },
} as const;

export const appNavigation = [
  { to: '/dashboard', label: appCopy.ui.navigation.dashboard, end: true },
  { to: '/dashboard/projects', label: appCopy.ui.navigation.projects, end: true },
  { to: '/tools/funnel-pages', label: appCopy.ui.navigation.funnelPages, end: false },
  { to: '/tools/nextland', label: appCopy.ui.navigation.nextland, end: false },
  { to: '/artifacts', label: appCopy.ui.navigation.artifacts, end: false },
  { to: '/admin', label: appCopy.ui.navigation.admin, end: false },
] as const;